changelog-seen = 2
profile = "user"

[llvm]
targets = "AArch64;RISCV;X86"

[build]
compiler-docs = true
docs = false
locked-deps = true

[rust]
channel = "nightly"
lld = true
jemalloc = true
debuginfo-level-std = 2
remap-debuginfo = true
new-symbol-mangling = true
split-debuginfo = "off"

[dist]
compression-formats = ["xz"]
compression-profile = "balanced"
