change-id = 121754

[build]
target = ["riscv32em-athena-zkvm-elf"]
extended = true
tools = ["cargo", "cargo-clippy", "clippy", "rustfmt"]
configure-args = []
cargo-native-static = true

[rust]
lld = true
llvm-tools = true
channel = "nightly"

[llvm]
targets = "AArch64;RISCV;X86"
