change-id = 125535

[build]
target = ["riscv32em-athena-zkvm-elf"]
extended = true
tools = ["cargo", "cargo-clippy", "clippy", "rustfmt"]
configure-args = []
cargo-native-static = true

# [target.riscv32em-athena-zkvm-elf]
# cc = "clang"
# cxx = "clang++"

[rust]
lld = true
llvm-tools = true
channel = "nightly"

[llvm]
targets = "AArch64;RISCV;X86"
