change-id = 125535

[build]
target = ["riscv32em-athena-zkvm-elf"]
extended = true
tools = ["cargo", "cargo-clippy", "clippy", "rustfmt"]
configure-args = []

[target.riscv32em-athena-zkvm-elf]
cc = "riscv32-unknown-elf-clang"
cxx = "riscv32-unknown-elf-clang++"
linker = "riscv32-unknown-elf-gcc"
ar = "riscv32-unknown-elf-ar"

[rust]
lld = true
llvm-tools = true
channel = "nightly"

[llvm]
targets = "AArch64;RISCV;X86"
