change-id = 125535

[build]
target = ["riscv32em-athena-zkvm-elf"]
extended = true
tools = ["cargo", "cargo-clippy", "clippy", "rustfmt"]
configure-args = []

[target.riscv32em-athena-zkvm-elf]
cc = "riscv64-unknown-elf-gcc"
cxx = "riscv64-unknown-elf-g++"

[rust]
lld = true
llvm-tools = true
channel = "nightly"

[llvm]
targets = "AArch64;RISCV;X86"
