name : Build and Release

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:

        # Maximaze runner space removing android-sdk and .net
        - name: Maximize build space
          uses: easimon/maximize-build-space@master
          with:
            root-reserve-mb: 512
            swap-size-mb: 1024
            remove-dotnet: 'true'
            remove-android: 'true'

        - uses: actions/checkout@v3

        # Install required packets
        - name: Install ninja
          run: |
              sudo apt update
              sudo apt-get -y install ninja-build

        # Clone things
        - name: Download Necessary sources
          run: ./01-clone.sh

        # Patch things
        - name: Apply patches
          run: ./02-patch.sh

        # Build Things
        #- name: Build rustc
        #  run: ./03-rustc-build.sh

        # Build Dists
        - name: Build dist
          run: ./04-build-dist.sh

        # Upload the final toolchain
        - uses: actions/upload-artifact@v3
          with:
            name: rv32e_dist
            path: rust/build/dist/dist_output.tar.gz
