name : Build and Release

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        # Install required packets
        - name: Install ninja
          run: |
              apt update
              apt-get install ninja-build -y

        # Clone things
        - name: Download Necessary sources
          run: ./01-clone.sh

        # Patch things
        - name: Apply patches
          run: ./02-patch.sh

        # Build Things
        - name: Build rustc
          run: ./03-rustc-build.sh

        # Upload the final toolchain
        - uses: actions/upload-artifact@v3
          with:
            name: x86_64-rv32e-toolchain
            path: $(pwd)/rust/build/host/stage1
