name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - README.md

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: [runs-on, runner=32cpu-linux-x64, "run-id=${{ github.run_id }}"]
            os: ubuntu
          - runner: [runs-on, runner=32cpu-linux-arm64, "run-id=${{ github.run_id }}"]
            os: ubuntu
          - runner: self-hosted
            os: macos
          - runner: macos-13
            os: macos
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Install nightly toolchain
        id: rustc-toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2024-05-29
          default: true

      - uses: lukka/get-cmake@v3.27.4

      - name: Show rust version
        run: |
          cargo version
          rustup toolchain list

      - name: Check out athenavm/rustc-rv32e-toolchain
        uses: actions/checkout@v4
        with:
          submodules: recursive
          path: toolchain

      - name: Check out athenavm/athena
        uses: actions/checkout@v3
        with:
          repository: athenavm/athena
          ref: main
          path: athena

      - name: Install ninja and riscv-tools
        if: matrix.os == 'ubuntu'
        run: |
          sudo apt update
          sudo apt-get -y install ninja-build gcc-riscv64-unknown-elf

      - name: Install ninja and riscv-tools
        if: matrix.os == 'macos'
        run: |
          brew install ninja
          brew tap riscv-software-src/riscv
          brew install riscv-tools

      - name: Build
        run:
          GITHUB_ACTIONS=false ATHENA_BUILD_DIR=$GITHUB_WORKSPACE/toolchain cargo run --bin cargo-athena -- athena
          build-toolchain
        working-directory: athena
